[theme]
primaryColor = "#1E90FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F4F7"
textColor = "#0E1117"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

[ui]
hideTopBar = true
